;;; ---------------------------------------------------------------------------
;; default els
;; /usr/share/emacs/site-lisp/
;; /usr/share/emacs24/site-lisp/elpa/

;;; ---------------------------------------------------------------------------
;; python commands

;; elpy-autopep8-fix-code 	elpy-check 	elpy-company-backend
;; elpy-config 	elpy-disable 	elpy-django
;; elpy-django-command 	elpy-django-runserver 	elpy-doc
;; elpy-enable 	elpy-find-file 	elpy-flymake-next-error
;; elpy-flymake-previous-error 	elpy-flymake-show-error 	elpy-format-code
;; elpy-goto-definition 	elpy-goto-definition-other-window 	elpy-importmagic-add-import
;; elpy-importmagic-fixup 	elpy-menu 	elpy-mode
;; elpy-modules-remove-modeline-lighter 	elpy-multiedit 	elpy-multiedit-add-overlay
;; elpy-multiedit-python-symbol-at-point 	elpy-multiedit-stop 	elpy-nav-backward-block
;; elpy-nav-backward-indent 	elpy-nav-expand-to-indentation 	elpy-nav-forward-block
;; elpy-nav-forward-indent 	elpy-nav-indent-shift-left 	elpy-nav-indent-shift-right
;; elpy-nav-move-line-or-region-down 	elpy-nav-move-line-or-region-up 	elpy-news
;; elpy-occur-definitions 	elpy-open-and-indent-line-above 	elpy-open-and-indent-line-below
;; elpy-refactor 	elpy-refactor-commit 	elpy-refactor-mode
;; elpy-refactor-options 	elpy-rgrep-symbol 	elpy-rpc-restart
;; elpy-set-project-root 	elpy-set-project-variable 	elpy-set-test-runner
;; elpy-shell-kill 	elpy-shell-kill-all 	elpy-shell-send-current-statement
;; elpy-shell-send-region-or-buffer 	elpy-shell-switch-to-buffer 	elpy-shell-switch-to-shell
;; elpy-test 	elpy-test-discover-runner 	elpy-test-django-runner
;; elpy-test-nose-runner 	elpy-test-pytest-runner 	elpy-test-trial-runner
;; elpy-use-cpython 	elpy-use-ipython 	elpy-version
;; elpy-yapf-fix-code

;; Python 	Python2
;; Python3 	py--beginning-of-form-intern
;; py--bounds-of-statements 	py--imenu-create-index-new
;; py--in-or-behind-or-before-a-docstring 	py--manage-windows-split
;; py--pdb-versioned 	py--string-fence-delete-spaces
;; py--unfontify-banner 	py--write-back-docstring
;; py-add-abbrev 	py-auto-completion-mode
;; py-autopair-check 	py-autopair-mode-off
;; py-autopair-mode-on 	py-autopep8
;; py-autopep8-buffer 	py-autopep8-enable-on-save
;; py-backward-block 	py-backward-block-bol
;; py-backward-block-or-clause 	py-backward-block-or-clause-bol
;; py-backward-buffer 	py-backward-class
;; py-backward-class-bol 	py-backward-clause
;; py-backward-clause-bol 	py-backward-comment
;; py-backward-declarations 	py-backward-decorator
;; py-backward-decorator-bol 	py-backward-def
;; py-backward-def-bol 	py-backward-def-or-class
;; py-backward-def-or-class-bol 	py-backward-elif-block
;; py-backward-elif-block-bol 	py-backward-else-block
;; py-backward-else-block-bol 	py-backward-except-block
;; py-backward-except-block-bol 	py-backward-expression
;; py-backward-for-block 	py-backward-for-block-bol
;; py-backward-function 	py-backward-if-block
;; py-backward-if-block-bol 	py-backward-indent
;; py-backward-indent-bol 	py-backward-into-nomenclature
;; py-backward-line 	py-backward-minor-block
;; py-backward-minor-block-bol 	py-backward-paragraph
;; py-backward-partial-expression 	py-backward-region
;; py-backward-same-level 	py-backward-section
;; py-backward-statement 	py-backward-statement-bol
;; py-backward-statements 	py-backward-top-level
;; py-backward-top-level-p 	py-backward-try-block
;; py-backward-try-block-bol 	py-beginning
;; py-beginning-of-block 	py-beginning-of-block-bol
;; py-beginning-of-block-current-column 	py-beginning-of-block-or-clause
;; py-beginning-of-class 	py-beginning-of-class-bol
;; py-beginning-of-clause 	py-beginning-of-clause-bol
;; py-beginning-of-comment 	py-beginning-of-declarations
;; py-beginning-of-decorator 	py-beginning-of-decorator-bol
;; py-beginning-of-def-or-class 	py-beginning-of-expression
;; py-beginning-of-line 	py-beginning-of-list-pps
;; py-beginning-of-minor-block 	py-beginning-of-partial-expression
;; py-beginning-of-section 	py-beginning-of-statement
;; py-beginning-of-statement-bol 	py-beginning-of-top-level
;; py-block 	py-block-down
;; py-block-or-clause 	py-block-up
;; py-boolswitch 	py-buffer
;; py-check-command 	py-choose-shell
;; py-choose-shell-by-path 	py-choose-shell-by-shebang
;; py-class 	py-class-at-point
;; py-class-down 	py-class-up
;; py-clause 	py-close-block
;; py-close-class 	py-close-def
;; py-close-def-or-class 	py-close-minor-block
;; py-close-statement 	py-comment-auto-fill
;; py-comment-auto-fill-off 	py-comment-auto-fill-on
;; py-comment-block 	py-comment-block-or-clause
;; py-comment-class 	py-comment-clause
;; py-comment-def 	py-comment-def-or-class
;; py-comment-indent 	py-comment-minor-block
;; py-comment-region 	py-comment-section
;; py-comment-statement 	py-comment-top-level
;; py-compute-indentation 	py-continuation-offset
;; py-copy-block 	py-copy-block-bol
;; py-copy-block-or-clause 	py-copy-block-or-clause-bol
;; py-copy-buffer 	py-copy-buffer-bol
;; py-copy-class 	py-copy-class-bol
;; py-copy-clause 	py-copy-clause-bol
;; py-copy-declarations 	py-copy-def
;; py-copy-def-bol 	py-copy-def-or-class
;; py-copy-def-or-class-bol 	py-copy-expression
;; py-copy-expression-bol 	py-copy-indent
;; py-copy-indent-bol 	py-copy-line
;; py-copy-line-bol 	py-copy-minor-block
;; py-copy-minor-block-bol 	py-copy-paragraph
;; py-copy-paragraph-bol 	py-copy-partial-expression
;; py-copy-partial-expression-bol 	py-copy-region
;; py-copy-region-bol 	py-copy-statement
;; py-copy-statement-bol 	py-copy-statements
;; py-copy-top-level 	py-copy-top-level-bol
;; py-count-indentation 	py-count-lines
;; py-current-defun 	py-declarations
;; py-dedent 	py-dedent-forward-line
;; py-dedicated-shell 	py-def
;; py-def-down 	py-def-or-class
;; py-def-or-class-down 	py-def-or-class-up
;; py-def-up 	py-delete-block
;; py-delete-block-or-clause 	py-delete-class
;; py-delete-clause 	py-delete-comment
;; py-delete-comments-in-block 	py-delete-comments-in-class
;; py-delete-comments-in-def-or-class 	py-delete-comments-in-region
;; py-delete-def 	py-delete-def-or-class
;; py-delete-elif-block 	py-delete-else-block
;; py-delete-except-block 	py-delete-expression
;; py-delete-for-block 	py-delete-if-block
;; py-delete-indent 	py-delete-line
;; py-delete-minor-block 	py-delete-paragraph
;; py-delete-partial-expression 	py-delete-section
;; py-delete-statement 	py-delete-top-level
;; py-delete-try-block 	py-describe-mode
;; py-describe-symbol 	py-documentation
;; py-down 	py-down-block
;; py-down-block-bol 	py-down-class
;; py-down-class-bol 	py-down-def
;; py-down-def-bol 	py-down-def-or-class
;; py-down-def-or-class-bol 	py-down-exception
;; py-down-minor-block 	py-down-minor-block-bol
;; py-down-statement 	py-down-top-level
;; py-edit-abbrevs 	py-edit-docstring
;; py-eldoc 	py-eldoc-function
;; py-electric-backspace 	py-electric-close
;; py-electric-colon 	py-electric-comment
;; py-electric-comment-p-off 	py-electric-comment-p-on
;; py-electric-delete 	py-electric-yank
;; py-empty-out-list-backward 	py-end
;; py-end-of-block 	py-end-of-block-or-clause
;; py-end-of-class 	py-end-of-clause
;; py-end-of-comment 	py-end-of-decorator
;; py-end-of-def-or-class 	py-end-of-expression
;; py-end-of-line 	py-end-of-list-position
;; py-end-of-partial-expression 	py-end-of-section
;; py-end-of-statement 	py-end-of-statement-bol
;; py-end-of-string 	py-end-of-top-level
;; py-execute-block 	py-execute-block-dedicated
;; py-execute-block-dedicated-switch 	py-execute-block-fast
;; py-execute-block-ipython 	py-execute-block-ipython-dedicated
;; py-execute-block-ipython-dedicated-switch 	py-execute-block-ipython-no-switch
;; py-execute-block-ipython-switch 	py-execute-block-ipython2.7
;; py-execute-block-ipython2.7-dedicated 	py-execute-block-ipython2.7-dedicated-switch
;; py-execute-block-ipython2.7-no-switch 	py-execute-block-ipython2.7-switch
;; py-execute-block-ipython3 	py-execute-block-ipython3-dedicated
;; py-execute-block-ipython3-dedicated-switch 	py-execute-block-ipython3-no-switch
;; py-execute-block-ipython3-switch 	py-execute-block-jython
;; py-execute-block-jython-dedicated 	py-execute-block-jython-dedicated-switch
;; py-execute-block-jython-no-switch 	py-execute-block-jython-switch
;; py-execute-block-no-switch 	py-execute-block-or-clause
;; py-execute-block-or-clause-dedicated 	py-execute-block-or-clause-dedicated-switch
;; py-execute-block-or-clause-fast 	py-execute-block-or-clause-ipython
;; py-execute-block-or-clause-ipython-dedicated 	py-execute-block-or-clause-ipython-dedicated-switch
;; py-execute-block-or-clause-ipython-no-switch 	py-execute-block-or-clause-ipython-switch
;; py-execute-block-or-clause-ipython2.7 	py-execute-block-or-clause-ipython2.7-dedicated
;; py-execute-block-or-clause-ipython2.7-dedicated-switch 	py-execute-block-or-clause-ipython2.7-no-switch
;; py-execute-block-or-clause-ipython2.7-switch 	py-execute-block-or-clause-ipython3
;; py-execute-block-or-clause-ipython3-dedicated 	py-execute-block-or-clause-ipython3-dedicated-switch
;; py-execute-block-or-clause-ipython3-no-switch 	py-execute-block-or-clause-ipython3-switch
;; py-execute-block-or-clause-jython 	py-execute-block-or-clause-jython-dedicated
;; py-execute-block-or-clause-jython-dedicated-switch 	py-execute-block-or-clause-jython-no-switch
;; py-execute-block-or-clause-jython-switch 	py-execute-block-or-clause-no-switch
;; py-execute-block-or-clause-python 	py-execute-block-or-clause-python-dedicated
;; py-execute-block-or-clause-python-dedicated-switch 	py-execute-block-or-clause-python-no-switch
;; py-execute-block-or-clause-python-switch 	py-execute-block-or-clause-python2
;; py-execute-block-or-clause-python2-dedicated 	py-execute-block-or-clause-python2-dedicated-switch
;; py-execute-block-or-clause-python2-no-switch 	py-execute-block-or-clause-python2-switch
;; py-execute-block-or-clause-python3 	py-execute-block-or-clause-python3-dedicated
;; py-execute-block-or-clause-python3-dedicated-switch 	py-execute-block-or-clause-python3-no-switch
;; py-execute-block-or-clause-python3-switch 	py-execute-block-or-clause-switch
;; py-execute-block-python 	py-execute-block-python-dedicated
;; py-execute-block-python-dedicated-switch 	py-execute-block-python-no-switch
;; py-execute-block-python-switch 	py-execute-block-python2
;; py-execute-block-python2-dedicated 	py-execute-block-python2-dedicated-switch
;; py-execute-block-python2-no-switch 	py-execute-block-python2-switch
;; py-execute-block-python3 	py-execute-block-python3-dedicated
;; py-execute-block-python3-dedicated-switch 	py-execute-block-python3-no-switch
;; py-execute-block-python3-switch 	py-execute-block-switch
;; py-execute-buffer 	py-execute-buffer-dedicated
;; py-execute-buffer-dedicated-switch 	py-execute-buffer-ipython
;; py-execute-buffer-ipython-dedicated 	py-execute-buffer-ipython-dedicated-switch
;; py-execute-buffer-ipython-no-switch 	py-execute-buffer-ipython-switch
;; py-execute-buffer-ipython2.7 	py-execute-buffer-ipython2.7-dedicated
;; py-execute-buffer-ipython2.7-dedicated-switch 	py-execute-buffer-ipython2.7-no-switch
;; py-execute-buffer-ipython2.7-switch 	py-execute-buffer-ipython3
;; py-execute-buffer-ipython3-dedicated 	py-execute-buffer-ipython3-dedicated-switch
;; py-execute-buffer-ipython3-no-switch 	py-execute-buffer-ipython3-switch
;; py-execute-buffer-jython 	py-execute-buffer-jython-dedicated
;; py-execute-buffer-jython-dedicated-switch 	py-execute-buffer-jython-no-switch
;; py-execute-buffer-jython-switch 	py-execute-buffer-no-switch
;; py-execute-buffer-python 	py-execute-buffer-python-dedicated
;; py-execute-buffer-python-dedicated-switch 	py-execute-buffer-python-no-switch
;; py-execute-buffer-python-switch 	py-execute-buffer-python2
;; py-execute-buffer-python2-dedicated 	py-execute-buffer-python2-dedicated-switch
;; py-execute-buffer-python2-no-switch 	py-execute-buffer-python2-switch
;; py-execute-buffer-python3 	py-execute-buffer-python3-dedicated
;; py-execute-buffer-python3-dedicated-switch 	py-execute-buffer-python3-no-switch
;; py-execute-buffer-python3-switch 	py-execute-buffer-switch
;; py-execute-class 	py-execute-class-dedicated
;; py-execute-class-dedicated-switch 	py-execute-class-fast
;; py-execute-class-ipython 	py-execute-class-ipython-dedicated
;; py-execute-class-ipython-dedicated-switch 	py-execute-class-ipython-no-switch
;; py-execute-class-ipython-switch 	py-execute-class-ipython2.7
;; py-execute-class-ipython2.7-dedicated 	py-execute-class-ipython2.7-dedicated-switch
;; py-execute-class-ipython2.7-no-switch 	py-execute-class-ipython2.7-switch
;; py-execute-class-ipython3 	py-execute-class-ipython3-dedicated
;; py-execute-class-ipython3-dedicated-switch 	py-execute-class-ipython3-no-switch
;; py-execute-class-ipython3-switch 	py-execute-class-jython
;; py-execute-class-jython-dedicated 	py-execute-class-jython-dedicated-switch
;; py-execute-class-jython-no-switch 	py-execute-class-jython-switch
;; py-execute-class-no-switch 	py-execute-class-python
;; py-execute-class-python-dedicated 	py-execute-class-python-dedicated-switch
;; py-execute-class-python-no-switch 	py-execute-class-python-switch
;; py-execute-class-python2 	py-execute-class-python2-dedicated
;; py-execute-class-python2-dedicated-switch 	py-execute-class-python2-no-switch
;; py-execute-class-python2-switch 	py-execute-class-python3
;; py-execute-class-python3-dedicated 	py-execute-class-python3-dedicated-switch
;; py-execute-class-python3-no-switch 	py-execute-class-python3-switch
;; py-execute-class-switch 	py-execute-clause
;; py-execute-clause-dedicated 	py-execute-clause-dedicated-switch
;; py-execute-clause-fast 	py-execute-clause-ipython
;; py-execute-clause-ipython-dedicated 	py-execute-clause-ipython-dedicated-switch
;; py-execute-clause-ipython-no-switch 	py-execute-clause-ipython-switch
;; py-execute-clause-ipython2.7 	py-execute-clause-ipython2.7-dedicated
;; py-execute-clause-ipython2.7-dedicated-switch 	py-execute-clause-ipython2.7-no-switch
;; py-execute-clause-ipython2.7-switch 	py-execute-clause-ipython3
;; py-execute-clause-ipython3-dedicated 	py-execute-clause-ipython3-dedicated-switch
;; py-execute-clause-ipython3-no-switch 	py-execute-clause-ipython3-switch
;; py-execute-clause-jython 	py-execute-clause-jython-dedicated
;; py-execute-clause-jython-dedicated-switch 	py-execute-clause-jython-no-switch
;; py-execute-clause-jython-switch 	py-execute-clause-no-switch
;; py-execute-clause-python 	py-execute-clause-python-dedicated
;; py-execute-clause-python-dedicated-switch 	py-execute-clause-python-no-switch
;; py-execute-clause-python-switch 	py-execute-clause-python2
;; py-execute-clause-python2-dedicated 	py-execute-clause-python2-dedicated-switch
;; py-execute-clause-python2-no-switch 	py-execute-clause-python2-switch
;; py-execute-clause-python3 	py-execute-clause-python3-dedicated
;; py-execute-clause-python3-dedicated-switch 	py-execute-clause-python3-no-switch
;; py-execute-clause-python3-switch 	py-execute-clause-switch
;; py-execute-def 	py-execute-def-dedicated
;; py-execute-def-dedicated-switch 	py-execute-def-fast
;; py-execute-def-ipython 	py-execute-def-ipython-dedicated
;; py-execute-def-ipython-dedicated-switch 	py-execute-def-ipython-no-switch
;; py-execute-def-ipython-switch 	py-execute-def-ipython2.7
;; py-execute-def-ipython2.7-dedicated 	py-execute-def-ipython2.7-dedicated-switch
;; py-execute-def-ipython2.7-no-switch 	py-execute-def-ipython2.7-switch
;; py-execute-def-ipython3 	py-execute-def-ipython3-dedicated
;; py-execute-def-ipython3-dedicated-switch 	py-execute-def-ipython3-no-switch
;; py-execute-def-ipython3-switch 	py-execute-def-jython
;; py-execute-def-jython-dedicated 	py-execute-def-jython-dedicated-switch
;; py-execute-def-jython-no-switch 	py-execute-def-jython-switch
;; py-execute-def-no-switch 	py-execute-def-or-class
;; py-execute-def-or-class-dedicated 	py-execute-def-or-class-dedicated-switch
;; py-execute-def-or-class-fast 	py-execute-def-or-class-ipython
;; py-execute-def-or-class-ipython-dedicated 	py-execute-def-or-class-ipython-dedicated-switch
;; py-execute-def-or-class-ipython-no-switch 	py-execute-def-or-class-ipython-switch
;; py-execute-def-or-class-ipython2.7 	py-execute-def-or-class-ipython2.7-dedicated
;; py-execute-def-or-class-ipython2.7-dedicated-switch 	py-execute-def-or-class-ipython2.7-no-switch
;; py-execute-def-or-class-ipython2.7-switch 	py-execute-def-or-class-ipython3
;; py-execute-def-or-class-ipython3-dedicated 	py-execute-def-or-class-ipython3-dedicated-switch
;; py-execute-def-or-class-ipython3-no-switch 	py-execute-def-or-class-ipython3-switch
;; py-execute-def-or-class-jython 	py-execute-def-or-class-jython-dedicated
;; py-execute-def-or-class-jython-dedicated-switch 	py-execute-def-or-class-jython-no-switch
;; py-execute-def-or-class-jython-switch 	py-execute-def-or-class-no-switch
;; py-execute-def-or-class-python 	py-execute-def-or-class-python-dedicated
;; py-execute-def-or-class-python-dedicated-switch 	py-execute-def-or-class-python-no-switch
;; py-execute-def-or-class-python-switch 	py-execute-def-or-class-python2
;; py-execute-def-or-class-python2-dedicated 	py-execute-def-or-class-python2-dedicated-switch
;; py-execute-def-or-class-python2-no-switch 	py-execute-def-or-class-python2-switch
;; py-execute-def-or-class-python3 	py-execute-def-or-class-python3-dedicated
;; py-execute-def-or-class-python3-dedicated-switch 	py-execute-def-or-class-python3-no-switch
;; py-execute-def-or-class-python3-switch 	py-execute-def-or-class-switch
;; py-execute-def-python 	py-execute-def-python-dedicated
;; py-execute-def-python-dedicated-switch 	py-execute-def-python-no-switch
;; py-execute-def-python-switch 	py-execute-def-python2
;; py-execute-def-python2-dedicated 	py-execute-def-python2-dedicated-switch
;; py-execute-def-python2-no-switch 	py-execute-def-python2-switch
;; py-execute-def-python3 	py-execute-def-python3-dedicated
;; py-execute-def-python3-dedicated-switch 	py-execute-def-python3-no-switch
;; py-execute-def-python3-switch 	py-execute-def-switch
;; py-execute-defun 	py-execute-expression
;; py-execute-expression-dedicated 	py-execute-expression-dedicated-switch
;; py-execute-expression-fast 	py-execute-expression-ipython
;; py-execute-expression-ipython-dedicated 	py-execute-expression-ipython-dedicated-switch
;; py-execute-expression-ipython-no-switch 	py-execute-expression-ipython-switch
;; py-execute-expression-ipython2.7 	py-execute-expression-ipython2.7-dedicated
;; py-execute-expression-ipython2.7-dedicated-switch 	py-execute-expression-ipython2.7-no-switch
;; py-execute-expression-ipython2.7-switch 	py-execute-expression-ipython3
;; py-execute-expression-ipython3-dedicated 	py-execute-expression-ipython3-dedicated-switch
;; py-execute-expression-ipython3-no-switch 	py-execute-expression-ipython3-switch
;; py-execute-expression-jython 	py-execute-expression-jython-dedicated
;; py-execute-expression-jython-dedicated-switch 	py-execute-expression-jython-no-switch
;; py-execute-expression-jython-switch 	py-execute-expression-no-switch
;; py-execute-expression-python 	py-execute-expression-python-dedicated
;; py-execute-expression-python-dedicated-switch 	py-execute-expression-python-no-switch
;; py-execute-expression-python-switch 	py-execute-expression-python2
;; py-execute-expression-python2-dedicated 	py-execute-expression-python2-dedicated-switch
;; py-execute-expression-python2-no-switch 	py-execute-expression-python2-switch
;; py-execute-expression-python3 	py-execute-expression-python3-dedicated
;; py-execute-expression-python3-dedicated-switch 	py-execute-expression-python3-no-switch
;; py-execute-expression-python3-switch 	py-execute-expression-switch
;; py-execute-file 	py-execute-file-ipython
;; py-execute-file-ipython-dedicated 	py-execute-file-ipython-dedicated-switch
;; py-execute-file-ipython-no-switch 	py-execute-file-ipython-switch
;; py-execute-file-jython 	py-execute-file-jython-dedicated
;; py-execute-file-jython-dedicated-switch 	py-execute-file-jython-no-switch
;; py-execute-file-jython-switch 	py-execute-file-python
;; py-execute-file-python-dedicated 	py-execute-file-python-dedicated-switch
;; py-execute-file-python-no-switch 	py-execute-file-python-switch
;; py-execute-file-python2 	py-execute-file-python2-dedicated
;; py-execute-file-python2-dedicated-switch 	py-execute-file-python2-no-switch
;; py-execute-file-python2-switch 	py-execute-file-python2.7
;; py-execute-file-python2.7-dedicated 	py-execute-file-python2.7-dedicated-switch
;; py-execute-file-python2.7-no-switch 	py-execute-file-python2.7-switch
;; py-execute-file-python3 	py-execute-file-python3-dedicated
;; py-execute-file-python3-dedicated-switch 	py-execute-file-python3-no-switch
;; py-execute-file-python3-switch 	py-execute-file-python3.2
;; py-execute-file-python3.2-dedicated 	py-execute-file-python3.2-dedicated-switch
;; py-execute-file-python3.2-no-switch 	py-execute-file-python3.2-switch
;; py-execute-file-python3.3 	py-execute-file-python3.3-dedicated
;; py-execute-file-python3.3-dedicated-switch 	py-execute-file-python3.3-no-switch
;; py-execute-file-python3.3-switch 	py-execute-for-block
;; py-execute-if-block 	py-execute-import-or-reload
;; py-execute-indent 	py-execute-indent-dedicated
;; py-execute-indent-dedicated-switch 	py-execute-indent-ipython
;; py-execute-indent-ipython-dedicated 	py-execute-indent-ipython-dedicated-switch
;; py-execute-indent-ipython-no-switch 	py-execute-indent-ipython-switch
;; py-execute-indent-ipython2.7 	py-execute-indent-ipython2.7-dedicated
;; py-execute-indent-ipython2.7-dedicated-switch 	py-execute-indent-ipython2.7-no-switch
;; py-execute-indent-ipython2.7-switch 	py-execute-indent-ipython3
;; py-execute-indent-ipython3-dedicated 	py-execute-indent-ipython3-dedicated-switch
;; py-execute-indent-ipython3-no-switch 	py-execute-indent-ipython3-switch
;; py-execute-indent-jython 	py-execute-indent-jython-dedicated
;; py-execute-indent-jython-dedicated-switch 	py-execute-indent-jython-no-switch
;; py-execute-indent-jython-switch 	py-execute-indent-no-switch
;; py-execute-indent-python 	py-execute-indent-python-dedicated
;; py-execute-indent-python-dedicated-switch 	py-execute-indent-python-no-switch
;; py-execute-indent-python-switch 	py-execute-indent-python2
;; py-execute-indent-python2-dedicated 	py-execute-indent-python2-dedicated-switch
;; py-execute-indent-python2-no-switch 	py-execute-indent-python2-switch
;; py-execute-indent-python3 	py-execute-indent-python3-dedicated
;; py-execute-indent-python3-dedicated-switch 	py-execute-indent-python3-no-switch
;; py-execute-indent-python3-switch 	py-execute-indent-switch
;; py-execute-line 	py-execute-line-dedicated
;; py-execute-line-dedicated-switch 	py-execute-line-ipython
;; py-execute-line-ipython-dedicated 	py-execute-line-ipython-dedicated-switch
;; py-execute-line-ipython-no-switch 	py-execute-line-ipython-switch
;; py-execute-line-ipython2.7 	py-execute-line-ipython2.7-dedicated
;; py-execute-line-ipython2.7-dedicated-switch 	py-execute-line-ipython2.7-no-switch
;; py-execute-line-ipython2.7-switch 	py-execute-line-ipython3
;; py-execute-line-ipython3-dedicated 	py-execute-line-ipython3-dedicated-switch
;; py-execute-line-ipython3-no-switch 	py-execute-line-ipython3-switch
;; py-execute-line-jython 	py-execute-line-jython-dedicated
;; py-execute-line-jython-dedicated-switch 	py-execute-line-jython-no-switch
;; py-execute-line-jython-switch 	py-execute-line-no-switch
;; py-execute-line-python 	py-execute-line-python-dedicated
;; py-execute-line-python-dedicated-switch 	py-execute-line-python-no-switch
;; py-execute-line-python-switch 	py-execute-line-python2
;; py-execute-line-python2-dedicated 	py-execute-line-python2-dedicated-switch
;; py-execute-line-python2-no-switch 	py-execute-line-python2-switch
;; py-execute-line-python3 	py-execute-line-python3-dedicated
;; py-execute-line-python3-dedicated-switch 	py-execute-line-python3-no-switch
;; py-execute-line-python3-switch 	py-execute-line-switch
;; py-execute-minor-block 	py-execute-minor-block-dedicated
;; py-execute-minor-block-dedicated-switch 	py-execute-minor-block-ipython
;; py-execute-minor-block-ipython-dedicated 	py-execute-minor-block-ipython-dedicated-switch
;; py-execute-minor-block-ipython-no-switch 	py-execute-minor-block-ipython-switch
;; py-execute-minor-block-ipython2.7 	py-execute-minor-block-ipython2.7-dedicated
;; py-execute-minor-block-ipython2.7-dedicated-switch 	py-execute-minor-block-ipython2.7-no-switch
;; py-execute-minor-block-ipython2.7-switch 	py-execute-minor-block-ipython3
;; py-execute-minor-block-ipython3-dedicated 	py-execute-minor-block-ipython3-dedicated-switch
;; py-execute-minor-block-ipython3-no-switch 	py-execute-minor-block-ipython3-switch
;; py-execute-minor-block-jython 	py-execute-minor-block-jython-dedicated
;; py-execute-minor-block-jython-dedicated-switch 	py-execute-minor-block-jython-no-switch
;; py-execute-minor-block-jython-switch 	py-execute-minor-block-no-switch
;; py-execute-minor-block-python 	py-execute-minor-block-python-dedicated
;; py-execute-minor-block-python-dedicated-switch 	py-execute-minor-block-python-no-switch
;; py-execute-minor-block-python-switch 	py-execute-minor-block-python2
;; py-execute-minor-block-python2-dedicated 	py-execute-minor-block-python2-dedicated-switch
;; py-execute-minor-block-python2-no-switch 	py-execute-minor-block-python2-switch
;; py-execute-minor-block-python3 	py-execute-minor-block-python3-dedicated
;; py-execute-minor-block-python3-dedicated-switch 	py-execute-minor-block-python3-no-switch
;; py-execute-minor-block-python3-switch 	py-execute-minor-block-switch
;; py-execute-paragraph 	py-execute-paragraph-dedicated
;; py-execute-paragraph-dedicated-switch 	py-execute-paragraph-ipython
;; py-execute-paragraph-ipython-dedicated 	py-execute-paragraph-ipython-dedicated-switch
;; py-execute-paragraph-ipython-no-switch 	py-execute-paragraph-ipython-switch
;; py-execute-paragraph-ipython2.7 	py-execute-paragraph-ipython2.7-dedicated
;; py-execute-paragraph-ipython2.7-dedicated-switch 	py-execute-paragraph-ipython2.7-no-switch
;; py-execute-paragraph-ipython2.7-switch 	py-execute-paragraph-ipython3
;; py-execute-paragraph-ipython3-dedicated 	py-execute-paragraph-ipython3-dedicated-switch
;; py-execute-paragraph-ipython3-no-switch 	py-execute-paragraph-ipython3-switch
;; py-execute-paragraph-jython 	py-execute-paragraph-jython-dedicated
;; py-execute-paragraph-jython-dedicated-switch 	py-execute-paragraph-jython-no-switch
;; py-execute-paragraph-jython-switch 	py-execute-paragraph-no-switch
;; py-execute-paragraph-python 	py-execute-paragraph-python-dedicated
;; py-execute-paragraph-python-dedicated-switch 	py-execute-paragraph-python-no-switch
;; py-execute-paragraph-python-switch 	py-execute-paragraph-python2
;; py-execute-paragraph-python2-dedicated 	py-execute-paragraph-python2-dedicated-switch
;; py-execute-paragraph-python2-no-switch 	py-execute-paragraph-python2-switch
;; py-execute-paragraph-python3 	py-execute-paragraph-python3-dedicated
;; py-execute-paragraph-python3-dedicated-switch 	py-execute-paragraph-python3-no-switch
;; py-execute-paragraph-python3-switch 	py-execute-paragraph-switch
;; py-execute-partial-expression 	py-execute-partial-expression-dedicated
;; py-execute-partial-expression-dedicated-switch 	py-execute-partial-expression-fast
;; py-execute-partial-expression-ipython 	py-execute-partial-expression-ipython-dedicated
;; py-execute-partial-expression-ipython-dedicated-switch 	py-execute-partial-expression-ipython-no-switch
;; py-execute-partial-expression-ipython-switch 	py-execute-partial-expression-ipython2.7
;; py-execute-partial-expression-ipython2.7-dedicated 	py-execute-partial-expression-ipython2.7-dedicated-switch
;; py-execute-partial-expression-ipython2.7-no-switch 	py-execute-partial-expression-ipython2.7-switch
;; py-execute-partial-expression-ipython3 	py-execute-partial-expression-ipython3-dedicated
;; py-execute-partial-expression-ipython3-dedicated-switch 	py-execute-partial-expression-ipython3-no-switch
;; py-execute-partial-expression-ipython3-switch 	py-execute-partial-expression-jython
;; py-execute-partial-expression-jython-dedicated 	py-execute-partial-expression-jython-dedicated-switch
;; py-execute-partial-expression-jython-no-switch 	py-execute-partial-expression-jython-switch
;; py-execute-partial-expression-no-switch 	py-execute-partial-expression-python
;; py-execute-partial-expression-python-dedicated 	py-execute-partial-expression-python-dedicated-switch
;; py-execute-partial-expression-python-no-switch 	py-execute-partial-expression-python-switch
;; py-execute-partial-expression-python2 	py-execute-partial-expression-python2-dedicated
;; py-execute-partial-expression-python2-dedicated-switch 	py-execute-partial-expression-python2-no-switch
;; py-execute-partial-expression-python2-switch 	py-execute-partial-expression-python3
;; py-execute-partial-expression-python3-dedicated 	py-execute-partial-expression-python3-dedicated-switch
;; py-execute-partial-expression-python3-no-switch 	py-execute-partial-expression-python3-switch
;; py-execute-partial-expression-switch 	py-execute-python-mode-v5
;; py-execute-region 	py-execute-region-dedicated
;; py-execute-region-dedicated-switch 	py-execute-region-default
;; py-execute-region-default-dedicated 	py-execute-region-in-shell
;; py-execute-region-ipython 	py-execute-region-ipython-dedicated
;; py-execute-region-ipython-dedicated-switch 	py-execute-region-ipython-no-switch
;; py-execute-region-ipython-switch 	py-execute-region-ipython2.7
;; py-execute-region-ipython2.7-dedicated 	py-execute-region-ipython2.7-dedicated-switch
;; py-execute-region-ipython2.7-no-switch 	py-execute-region-ipython2.7-switch
;; py-execute-region-ipython3 	py-execute-region-ipython3-dedicated
;; py-execute-region-ipython3-dedicated-switch 	py-execute-region-ipython3-no-switch
;; py-execute-region-ipython3-switch 	py-execute-region-jython
;; py-execute-region-jython-dedicated 	py-execute-region-jython-dedicated-switch
;; py-execute-region-jython-no-switch 	py-execute-region-jython-switch
;; py-execute-region-no-switch 	py-execute-region-pdb
;; py-execute-region-python 	py-execute-region-python-dedicated
;; py-execute-region-python-dedicated-switch 	py-execute-region-python-no-switch
;; py-execute-region-python-switch 	py-execute-region-python2
;; py-execute-region-python2-dedicated 	py-execute-region-python2-dedicated-switch
;; py-execute-region-python2-no-switch 	py-execute-region-python2-switch
;; py-execute-region-python3 	py-execute-region-python3-dedicated
;; py-execute-region-python3-dedicated-switch 	py-execute-region-python3-no-switch
;; py-execute-region-python3-switch 	py-execute-region-switch
;; py-execute-section 	py-execute-section-fast
;; py-execute-section-ipython 	py-execute-section-ipython2.7
;; py-execute-section-ipython3 	py-execute-section-jython
;; py-execute-section-python 	py-execute-section-python2
;; py-execute-section-python3 	py-execute-statement
;; py-execute-statement-dedicated 	py-execute-statement-dedicated-switch
;; py-execute-statement-fast 	py-execute-statement-ipython
;; py-execute-statement-ipython-dedicated 	py-execute-statement-ipython-dedicated-switch
;; py-execute-statement-ipython-no-switch 	py-execute-statement-ipython-switch
;; py-execute-statement-ipython2.7 	py-execute-statement-ipython2.7-dedicated
;; py-execute-statement-ipython2.7-dedicated-switch 	py-execute-statement-ipython2.7-no-switch
;; py-execute-statement-ipython2.7-switch 	py-execute-statement-ipython3
;; py-execute-statement-ipython3-dedicated 	py-execute-statement-ipython3-dedicated-switch
;; py-execute-statement-ipython3-no-switch 	py-execute-statement-ipython3-switch
;; py-execute-statement-jython 	py-execute-statement-jython-dedicated
;; py-execute-statement-jython-dedicated-switch 	py-execute-statement-jython-no-switch
;; py-execute-statement-jython-switch 	py-execute-statement-no-switch
;; py-execute-statement-pdb 	py-execute-statement-python
;; py-execute-statement-python-dedicated 	py-execute-statement-python-dedicated-switch
;; py-execute-statement-python-no-switch 	py-execute-statement-python-switch
;; py-execute-statement-python2 	py-execute-statement-python2-dedicated
;; py-execute-statement-python2-dedicated-switch 	py-execute-statement-python2-no-switch
;; py-execute-statement-python2-switch 	py-execute-statement-python3
;; py-execute-statement-python3-dedicated 	py-execute-statement-python3-dedicated-switch
;; py-execute-statement-python3-no-switch 	py-execute-statement-python3-switch
;; py-execute-statement-switch 	py-execute-string
;; py-execute-string-dedicated 	py-execute-top-level
;; py-execute-top-level-dedicated 	py-execute-top-level-dedicated-switch
;; py-execute-top-level-fast 	py-execute-top-level-ipython
;; py-execute-top-level-ipython-dedicated 	py-execute-top-level-ipython-dedicated-switch
;; py-execute-top-level-ipython-no-switch 	py-execute-top-level-ipython-switch
;; py-execute-top-level-ipython2.7 	py-execute-top-level-ipython2.7-dedicated
;; py-execute-top-level-ipython2.7-dedicated-switch 	py-execute-top-level-ipython2.7-no-switch
;; py-execute-top-level-ipython2.7-switch 	py-execute-top-level-ipython3
;; py-execute-top-level-ipython3-dedicated 	py-execute-top-level-ipython3-dedicated-switch
;; py-execute-top-level-ipython3-no-switch 	py-execute-top-level-ipython3-switch
;; py-execute-top-level-jython 	py-execute-top-level-jython-dedicated
;; py-execute-top-level-jython-dedicated-switch 	py-execute-top-level-jython-no-switch
;; py-execute-top-level-jython-switch 	py-execute-top-level-no-switch
;; py-execute-top-level-python 	py-execute-top-level-python-dedicated
;; py-execute-top-level-python-dedicated-switch 	py-execute-top-level-python-no-switch
;; py-execute-top-level-python-switch 	py-execute-top-level-python2
;; py-execute-top-level-python2-dedicated 	py-execute-top-level-python2-dedicated-switch
;; py-execute-top-level-python2-no-switch 	py-execute-top-level-python2-switch
;; py-execute-top-level-python3 	py-execute-top-level-python3-dedicated
;; py-execute-top-level-python3-dedicated-switch 	py-execute-top-level-python3-no-switch
;; py-execute-top-level-python3-switch 	py-execute-top-level-switch
;; py-execute-try-block 	py-expression
;; py-fast-complete 	py-fast-process
;; py-fetch-docu 	py-fetch-py-master-file
;; py-fill-comment 	py-fill-labelled-string
;; py-fill-paragraph 	py-fill-paren
;; py-fill-string 	py-fill-string-django
;; py-fill-string-onetwo 	py-fill-string-pep-257
;; py-fill-string-pep-257-nn 	py-fill-string-symmetric
;; py-find-definition 	py-find-function
;; py-find-imports 	py-flake8-help
;; py-flake8-run 	py-flycheck-mode
;; py-fontify-shell-buffer-p-off 	py-fontify-shell-buffer-p-on
;; py-force-local-shell-off 	py-force-local-shell-on
;; py-forward-block 	py-forward-block-bol
;; py-forward-block-or-clause 	py-forward-block-or-clause-bol
;; py-forward-buffer 	py-forward-class
;; py-forward-class-bol 	py-forward-clause
;; py-forward-clause-bol 	py-forward-comment
;; py-forward-declarations 	py-forward-decorator
;; py-forward-def 	py-forward-def-bol
;; py-forward-def-or-class 	py-forward-def-or-class-bol
;; py-forward-elif-block 	py-forward-elif-block-bol
;; py-forward-else-block 	py-forward-else-block-bol
;; py-forward-except-block 	py-forward-except-block-bol
;; py-forward-expression 	py-forward-for-block
;; py-forward-for-block-bol 	py-forward-function
;; py-forward-if-block 	py-forward-if-block-bol
;; py-forward-indent 	py-forward-indent-bol
;; py-forward-into-nomenclature 	py-forward-line
;; py-forward-minor-block 	py-forward-minor-block-bol
;; py-forward-paragraph 	py-forward-partial-expression
;; py-forward-region 	py-forward-section
;; py-forward-statement 	py-forward-statement-bol
;; py-forward-statements 	py-forward-top-level
;; py-forward-top-level-bol 	py-forward-try-block
;; py-forward-try-block-bol 	py-function-at-point
;; py-go-to-beginning-of-comment 	py-goto-exception
;; py-guess-default-python 	py-guess-indent-offset
;; py-guess-pdb-path 	py-guess-py-install-directory
;; py-help-at-point 	py-hide-block
;; py-hide-block-or-clause 	py-hide-class
;; py-hide-clause 	py-hide-comment
;; py-hide-def 	py-hide-def-or-class
;; py-hide-elif-block 	py-hide-else-block
;; py-hide-except-block 	py-hide-expression
;; py-hide-for-block 	py-hide-if-block
;; py-hide-indent 	py-hide-line
;; py-hide-minor-block 	py-hide-paragraph
;; py-hide-partial-expression 	py-hide-region
;; py-hide-section 	py-hide-show
;; py-hide-statement 	py-hide-top-level
;; py-highlight-indentation-off 	py-highlight-indentation-on
;; py-hungry-delete-backwards 	py-hungry-delete-forward
;; py-in-comment-p 	py-in-statement-p
;; py-in-string-p 	py-in-triplequoted-string-p
;; py-indent 	py-indent-and-forward
;; py-indent-forward-line 	py-indent-line
;; py-indent-line-outmost 	py-indent-or-complete
;; py-indent-region 	py-indent-tabs-mode
;; py-indent-tabs-mode-off 	py-indent-tabs-mode-on
;; py-indentation-of-statement 	py-info-current-defun
;; py-info-lookup-symbol 	py-insert-default-shebang
;; py-insert-super 	py-install-directory-check
;; py-install-local-shells 	py-install-search-local
;; py-ipython--module-completion-import 	py-ipython-shell-command-on-region
;; py-ipython-shell-mode 	py-jump-on-exception-off
;; py-jump-on-exception-on 	py-kill-block
;; py-kill-block-or-clause 	py-kill-buffer-unconditional
;; py-kill-class 	py-kill-clause
;; py-kill-comment 	py-kill-declarations
;; py-kill-def 	py-kill-def-or-class
;; py-kill-default-shell-unconditional 	py-kill-elif-block
;; py-kill-else-block 	py-kill-except-block
;; py-kill-expression 	py-kill-for-block
;; py-kill-if-block 	py-kill-indent
;; py-kill-line 	py-kill-minor-block
;; py-kill-minor-expression 	py-kill-paragraph
;; py-kill-partial-expression 	py-kill-section
;; py-kill-shell-unconditional 	py-kill-statement
;; py-kill-statements 	py-kill-top-level
;; py-kill-try-block 	py-leave-comment-or-string-backward
;; py-line 	py-line-at-point
;; py-line-to-printform-python2 	py-load-file
;; py-load-pymacs 	py-load-skeletons
;; py-look-downward-for-clause 	py-mark-block
;; py-mark-block-or-clause 	py-mark-class
;; py-mark-clause 	py-mark-comment
;; py-mark-def 	py-mark-def-or-class
;; py-mark-elif-block 	py-mark-else-block
;; py-mark-except-block 	py-mark-expression
;; py-mark-for-block 	py-mark-if-block
;; py-mark-indent 	py-mark-line
;; py-mark-minor-block 	py-mark-paragraph
;; py-mark-partial-expression 	py-mark-section
;; py-mark-statement 	py-mark-top-level
;; py-mark-try-block 	py-markup-region-as-section
;; py-match-paren 	py-match-paren-mode
;; py-menu 	py-minor-block
;; py-minor-block-down 	py-minor-block-up
;; py-mouseto-exception 	py-narrow-to-block
;; py-narrow-to-block-or-clause 	py-narrow-to-class
;; py-narrow-to-clause 	py-narrow-to-def
;; py-narrow-to-def-or-class 	py-narrow-to-statement
;; py-nesting-level 	py-newline-and-close-block
;; py-newline-and-dedent 	py-newline-and-indent
;; py-next-statement 	py-output-buffer-filter
;; py-output-filter 	py-paragraph
;; py-partial-expression 	py-pdb
;; py-pdb-break 	py-pdb-execute-statement
;; py-pdb-help 	py-pdbtrack-toggle-stack-tracking
;; py-pep8-help 	py-pep8-run
;; py-printform-insert 	py-proc
;; py-process-file 	py-process-region-fast
;; py-pychecker-run 	py-pyflakes-help
;; py-pyflakes-run 	py-pyflakespep8-help
;; py-pyflakespep8-run 	py-pylint-doku
;; py-pylint-help 	py-pylint-run
;; py-python-current-environment 	py-python-shell-mode
;; py-python-version 	py-python2-shell-complete
;; py-python3-shell-complete 	py-region
;; py-remove-overlays-at-point 	py-rotate-shell-fontify-style
;; py-script-complete 	py-sectionize-region
;; py-send-file 	py-send-region-ipython
;; py-send-string 	py-set-command-args
;; py-set-django-docstring-style 	py-set-ipython-completion-command-string
;; py-set-load-path 	py-set-nil-docstring-style
;; py-set-onetwo-docstring-style 	py-set-pep-257-docstring-style
;; py-set-pep-257-nn-docstring-style 	py-set-symmetric-docstring-style
;; py-shell 	py-shell-command-on-region
;; py-shell-complete 	py-shell-dedicated
;; py-shell-get-process 	py-shell-menu
;; py-shell-redirect-send-command-to-process 	py-shell-send-file
;; py-shell-switch-buffers-on-execute-off 	py-shell-switch-buffers-on-execute-on
;; py-shift-block-left 	py-shift-block-or-clause-left
;; py-shift-block-or-clause-right 	py-shift-block-right
;; py-shift-class-left 	py-shift-class-right
;; py-shift-clause-left 	py-shift-clause-right
;; py-shift-comment-left 	py-shift-comment-right
;; py-shift-def-left 	py-shift-def-or-class-left
;; py-shift-def-or-class-right 	py-shift-def-right
;; py-shift-indent-left 	py-shift-indent-right
;; py-shift-left 	py-shift-minor-block-left
;; py-shift-minor-block-right 	py-shift-paragraph-left
;; py-shift-paragraph-right 	py-shift-region-left
;; py-shift-region-right 	py-shift-right
;; py-shift-statement-left 	py-shift-statement-right
;; py-shift-top-level-left 	py-shift-top-level-right
;; py-show-block 	py-show-block-or-clause
;; py-show-class 	py-show-clause
;; py-show-comment 	py-show-def
;; py-show-def-or-class 	py-show-elif-block
;; py-show-else-block 	py-show-except-block
;; py-show-expression 	py-show-for-block
;; py-show-if-block 	py-show-indent
;; py-show-line 	py-show-minor-block
;; py-show-paragraph 	py-show-partial-expression
;; py-show-region 	py-show-section
;; py-show-statement 	py-show-top-level
;; py-smart-indentation-off 	py-smart-indentation-on
;; py-smart-operator-check 	py-smart-operator-mode-p-off
;; py-smart-operator-mode-p-on 	py-sort-imports
;; py-split-window-on-execute-off 	py-split-window-on-execute-on
;; py-split-windows-on-execute-off 	py-split-windows-on-execute-on
;; py-statement 	py-statements
;; py-switch-buffers-on-execute-p-off 	py-switch-buffers-on-execute-p-on
;; py-switch-imenu-index-function 	py-switch-shell
;; py-switch-shells 	py-switch-to-python
;; py-switch-to-shell 	py-symbol-at-point
;; py-toggle-autopair-mode 	py-toggle-execute-use-temp-file
;; py-toggle-highlight-indentation 	py-toggle-indent-tabs-mode
;; py-toggle-local-default-use 	py-toggle-sexp-function
;; py-toggle-shell 	py-toggle-shell-switch-buffers-on-execute
;; py-toggle-shells 	py-toggle-smart-indentation
;; py-toggle-split-window-function 	py-toggle-split-window-on-execute-function
;; py-toggle-split-windows-on-execute 	py-toggle-switch-buffers-on-execute
;; py-top-level 	py-uncomment
;; py-underscore-word-syntax-p-off 	py-underscore-word-syntax-p-on
;; py-unload-python-el 	py-up
;; py-up-block 	py-up-block-bol
;; py-up-class 	py-up-class-bol
;; py-up-def 	py-up-def-bol
;; py-up-def-or-class 	py-up-def-or-class-bol
;; py-up-exception 	py-up-minor-block
;; py-up-minor-block-bol 	py-up-statement
;; py-update-gud-pdb-history 	py-update-imports
;; py-use-current-dir-when-execute-p-off 	py-use-current-dir-when-execute-p-on
;; py-version 	py-which-def-or-class
;; py-which-execute-file-command 	py-which-python
;; py-which-shell 	pychecker-flymake-mode
;; pyflakes 	pyflakes-flymake-mode
;; pyflakes-help 	pyflakespep8
;; pyflakespep8-flymake-mode 	pyhotn
;; pyhton 	pylint
;; pylint-doku 	pylint-flymake-mode
;; pylint-help 	pylint-insert-ignore-comment
;; pyt 	python
;; python-check 	python-dedicated
;; python-dedicated-switch 	python-eldoc-at-point
;; python-fill-paragraph 	python-indent-dedent-line
;; python-indent-dedent-line-backspace 	python-indent-guess-indent-offset
;; python-indent-shift-left 	python-indent-shift-right
;; python-menu 	python-mode
;; python-mode-v5-behavior-p-off 	python-mode-v5-behavior-p-on
;; python-nav-backward-block 	python-nav-backward-defun
;; python-nav-backward-sexp 	python-nav-backward-sexp-safe
;; python-nav-backward-statement 	python-nav-backward-up-list
;; python-nav-beginning-of-block 	python-nav-beginning-of-statement
;; python-nav-end-of-block 	python-nav-end-of-defun
;; python-nav-end-of-statement 	python-nav-forward-block
;; python-nav-forward-defun 	python-nav-forward-sexp
;; python-nav-forward-sexp-safe 	python-nav-forward-statement
;; python-nav-if-name-main 	python-nav-up-list
;; python-no-switch 	python-pep8
;; python-shell-completion-complete-or-indent 	python-shell-send-buffer
;; python-shell-send-defun 	python-shell-send-file
;; python-shell-send-region 	python-shell-send-string
;; python-shell-switch-to-shell 	python-skeleton--else
;; python-skeleton--except 	python-skeleton--finally
;; python-skeleton-class 	python-skeleton-def
;; python-skeleton-for 	python-skeleton-if
;; python-skeleton-try 	python-skeleton-while
;; python-switch 	python-switch-dedicated
;; python2 	python2-dedicated
;; python2-dedicated-switch 	python2-no-switch
;; python2-switch 	python2-switch-dedicated
;; python3 	python3-dedicated
;; python3-dedicated-switch 	python3-no-switch
;; python3-switch 	python3-switch-dedicated
;; pyvenv-activate 	pyvenv-deactivate
;; pyvenv-menu 	pyvenv-mode
;; pyvenv-restart-python 	pyvenv-tracking-mode
;; pyvenv-workon
